### PR TITLE
Added instructions for branch creation.

### PR DESCRIPTION
**Pull request by UkrainianEngineer**
This is just an example how pull requests should looks like after your changes.

### CODE REVIEW

**Comment by Sasha1152** [comment]
:+1:

**Comment by UkrainianEngineer** [comment]
@RomanPryima , @kate-ka, @nguyenduchuy , guys, please react somehow: write a comments or set a 👍  symbol. Thanks!

**Comment by RomanPryima** [comment]
:+1:

**Comment by kate-ka** [comment]
👍

**Pull request merged**
