### PR TITLE
Please check the first draft of landing page. Pictures may be cropped and links have to be changed into appropriate ones.

### PR DESCRIPTION
**Pull request by RomanPryima**

### CODE REVIEW

**Comment by UkrainianEngineer** [comment]
So, here I can see a  pull request with some networking, but description about landing page....
Something is wrong?

**Comment by UkrainianEngineer** [comment]
Another important things are:
1) You're trying to pull `master` branch into your `Roman` branch, but not vice versa.Is it really what you want?
2) You're gathering all of your work (related to Travel Platform and not related) in the same branch. If we decided to merge something from your branch into `release` branch, we'll merge all of this stuff what is terrible.
To understand what I mean, you can see here:
https://github.com/pivancy/itea-advanced-python/compare/release...Roman

How to fix this situation?
As I mentioned, we may and should create separate branch for each task. It may be names like: ITEA-<id_of_trello_task>.
As an example it may be: ITEA-1, ITEA-2, ...



P.S. @kate-ka , @nguyenduchuy , @Sasha1152  guys, I want to share this information with each of you. Please, read my current comment.

**Comment by RomanPryima** [comment]
@pivancy 
First of all, who is StrongBrain and what does he do in my branch?
Secondly, I'll try create 2 new branches for tasks I'm working on in trello.
What should be saved in  these branches? All the files or only files belonging to the task?

Can you see the draft of the page in my branch?

**Comment by UkrainianEngineer** [comment]
@RomanPryima StrongBrain - it's my second Github account, so keep calm. :)

You should have just a needed files/changes to related tasks in your branches.

I can see, but it's difficult to review it.

**Comment by RomanPryima** [comment]
I have to learn more about github.
If I have a time today I correct branches today. Otherwise - on Monday.

**Comment by RomanPryima** [comment]
Please correct me if I did something wrong

**Comment by UkrainianEngineer** [comment]
@RomanPryima  First of all you've created a  wrong pull request from `master` branch into `itea-...`

**Pull request closed without merging**
